version: '3'

services:
  db:
    image: mariadb:10.4
    container_name: db
    ports: 
      - 8001:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=charts
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  web:
    image: andersonralves/webserver:1.0
    container_name: web
    ports:
      - 8002:80
      - 3000:3000
    volumes:
      - ./:/var/www/html
    depends_on: 
      - db
    links:
      - db
    tty: true
        
